In [1]:
import numpy as np

In [3]:
a = np.array([1,'text',1/3,True])
print(a)

['1' 'text' '0.3333333333333333' 'True']


In [24]:
print(np.zeros(16))
print(np.ones(16))
print(np.arange(0,8,0.5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [25]:
print(np.linspace(0,10,16))

[ 0.          0.66666667  1.33333333  2.          2.66666667  3.33333333
  4.          4.66666667  5.33333333  6.          6.66666667  7.33333333
  8.          8.66666667  9.33333333 10.        ]


In [41]:
a = np.random.rand(4,3)
print(a)

[[0.23467097 0.40208674 0.69116945]
 [0.78958846 0.15562906 0.87352146]
 [0.12987639 0.8903616  0.50039813]
 [0.17250486 0.02323392 0.51639646]]


In [44]:
a.shape

(4, 3)

In [43]:
a[0,0]

0.23467097451293362

In [46]:
print(a[0])
print(a[0,:])

[0.23467097 0.40208674 0.69116945]
[0.23467097 0.40208674 0.69116945]


In [50]:
a[:,0]

array([0.23467097, 0.78958846, 0.12987639, 0.17250486])

In [52]:
a[:2,0]

array([0.23467097, 0.78958846])

In [47]:
a.T

array([[0.23467097, 0.78958846, 0.12987639, 0.17250486],
       [0.40208674, 0.15562906, 0.8903616 , 0.02323392],
       [0.69116945, 0.87352146, 0.50039813, 0.51639646]])

In [56]:
print(a.mean())
print(a.std())

0.4482864601096868
0.2958903938527235


In [57]:
print(a.mean(axis=0))
print(a.std(axis=0))

[0.33166017 0.36782783 0.64537138]
[0.26699828 0.3309035  0.15149398]


In [59]:
print(a.mean(axis=1))
print(a.std(axis=1))

[0.44264239 0.60624633 0.50687871 0.23737841]
[0.18855819 0.32047166 0.3105006  0.20649254]


In [60]:
a+1

array([[1.23467097, 1.40208674, 1.69116945],
       [1.78958846, 1.15562906, 1.87352146],
       [1.12987639, 1.8903616 , 1.50039813],
       [1.17250486, 1.02323392, 1.51639646]])

In [61]:
a.flatten()

array([0.23467097, 0.40208674, 0.69116945, 0.78958846, 0.15562906,
       0.87352146, 0.12987639, 0.8903616 , 0.50039813, 0.17250486,
       0.02323392, 0.51639646])

In [ ]:
a.res()

In [33]:
a+b

array([[1.40577882, 1.08064087, 1.18556468],
       [1.00010981, 0.78303783, 1.20238066],
       [1.23707742, 0.46179951, 0.64546158],
       [1.26416765, 1.70985744, 1.52539127]])

In [34]:
a*b

array([[0.44660978, 0.09352872, 0.34938256],
       [0.18790383, 0.01892153, 0.25716522],
       [0.37459233, 0.05312051, 0.04336181],
       [0.31072541, 0.72986323, 0.5588904 ]])

In [40]:
np.cross(a,b)

array([[-0.47967036, -0.32123414,  0.86157186],
       [-0.18790037, -0.02318083,  0.17138704],
       [ 0.10486816, -0.24729372, -0.02406017],
       [-0.30745324,  0.6455127 , -0.46877301]])